### ISSUE TITLE
Explosions sometimes spawn plating rather than the base_turf

### ISSUE THREAD

**Issue by SamHPurp** [Planetfall/PlanetfallSS13#3]
As the title says, rather than changing to the `base_turf` sometimes the explosions are making it plating, and I cannot work out why yet.

**Comment by owenowen212** [comment]
Couldn't recreate this, any hints?

**Comment by SamHPurp** [comment]
I'm assuming its the scorching mechanic... tiles getting burned, but not having burn equivalents and being reverted to plating.... thats where I'd look.

**Comment by owenowen212** [comment]
It seems this issue only applies to children of ``/floor``. There  are ``make_plating()`` and ``break_tile_to_plating`` procs that are called when an explosion occurs on turfs that are children of /floor.
